name: Cypress Component Tests
on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@4.3.0
        with:
          node-version: 18 

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run Cypress component tests
      - name: Cypress.io
        uses: cypress-io/github-action@v6.7.16 
        with:
          component: true
          e2e: false
